services:
  db:
    image: postgres:18.3-trixie
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cdg
    volumes:
      - ./data:/var/lib/postgresql
volumes:
  pgdata:
